### ISSUE TITLE
Could not find folder column

### ISSUE THREAD

**Issue by 97-109-107** [evmcl/erudite#1]
Using the following settings:
````
processors = mobi

mobi.type = ebookconvert
mobi.filetype = mobi
mobi.author = Someone on the Web
mobi.option = --change-justification=left
mobi.then = save
mobi.saveto = /home/amk/Documents/instapaper-erudite/
````
I get the following error:
````
█▓▒░ java -jar erudite.jar process

com.evanmclean.erudite.instapaper.HasInstapaperLayoutChangedException: Could not find folder column.
	at com.evanmclean.erudite.instapaper.Instapaper._getFolders(Instapaper.java:425)
	at com.evanmclean.erudite.instapaper.Instapaper.getReadLaterFolder(Instapaper.java:403)
	at com.evanmclean.erudite.instapaper.InstapaperSource.getArticles(InstapaperSource.java:103)
	at com.evanmclean.erudite.cli.Main.process(Main.java:295)
	at com.evanmclean.erudite.cli.Main._main(Main.java:98)
	at com.evanmclean.erudite.cli.Main.main(Main.java:55)
````

**Comment by evmcl** [comment]
Hi Antoni,

Just tried with the [2.3](https://github.com/evmcl/erudite/releases/tag/v2.3) release and it worked properly for me.

Perhaps you need to initialise your credentials again. e.g., `java -jar erudite.jar init instapaper`

Or maybe the Instapaper site was having a weird moment and it was a transient problem.

Let me know how you get on.

E.

**Comment by 97-109-107** [comment]
I just tried, and it seems I haven't missed that as step:

````
The session file already exists.
Delete or rename /home/amk/.erudite/session.dat first.
````
And here's the log tail
````
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The full story of Jon Carnes, Silvercorp and the BCSC
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Peter Moore - He Never Sat an Exam
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: https://www.google.pl/search?q=ipod classic 7
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: North Dakota's Norway experiment
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: …
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Black Gooey Universe - unbag - Issue 2: End
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The Avon Lady’s Makeover
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The big data lie has been exposed – but just blaming Facebook won’t fix things
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: A Quick (Battle) Field Guide to the New Culture Wars
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Being frugal is for the rich
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Op-Ed | Blockchains Could Upend the Fashion Business
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The Distributed Monument
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: In the 1950s everybody cool was a little alienated. What changed? – Martin Jay | Aeon Essays
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Say goodbye to the information age: it’s all about reputation now – Gloria Origgi | Aeon Ideas
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The Real Future of Work
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Due Process | Lewis H. Lapham
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: Crafting a life
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The 4 Brain Superpowers You Need to Be a Successful Leader, According to Neuroscience
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: How the Irish Teach Us to Die
15:46:41 [main] TRACE c.e.e.i.Instapaper$Folder Article: The Lottery Hackers
15:46:41 [main] TRACE c.e.e.i.Instapaper Folder: Read Later => https://www.instapaper.com/u
15:46:41 [main] ERROR c.e.e.cli.Main 
com.evanmclean.erudite.instapaper.HasInstapaperLayoutChangedException: Could not find folder column.
	at com.evanmclean.erudite.instapaper.Instapaper._getFolders(Instapaper.java:425)
	at com.evanmclean.erudite.instapaper.Instapaper.getReadLaterFolder(Instapaper.java:403)
	at com.evanmclean.erudite.instapaper.InstapaperSource.getArticles(InstapaperSource.java:103)
	at com.evanmclean.erudite.cli.Main.process(Main.java:295)
	at com.evanmclean.erudite.cli.Main._main(Main.java:98)
	at com.evanmclean.erudite.cli.Main.main(Main.java:55)
15:46:41 [main] TRACE c.e.e.cli.Main Exit value: 1

````

**Comment by evmcl** [comment]
Hi Antoni,

I've just created release [2.4](https://github.com/evmcl/erudite/releases/tag/v2.4) which should fix this issue.

Thanks for the extra log information. Seeing that it was reading the names of the articles clued me in that your session data was okay, so I dug a bit deeper and figured out what was going on. It was a bug that is triggered if you have no added folders in Instapaper (I've always had extra folders so never tripped on that before).

Best regards and thanks for using Erudite!

E.
